version: '3.1'
services:
  db:
    image: mysql:8.0-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anime
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\rafae\Documentos\database\mysql\devrafa_data:/var/lib/mysql

volumes:
  devrafa_data: